# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30a9fd6e3a5b21a8363e01a3116a897c87361bb68c37bcf2e8d5a63bf2ce1826ad4eefb9918538cf13c146c48b436f5052664c98f1b40f808569cef1d33e9df2

test:
  secret_key_base: c37c54d8f21a28f8983fbf3d9698db7581b40ef551f7593f6df7accaaa5fdda0fa2e18425dbaa034c95c3aa967415d5b41a140caacec3b856e6cc9f83b8a54ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
